---
# tasks file for SeiichiDomyo.libxfs

- hosts: centos5
  sudo: yes

  vars:
    xfsprogs_rpms_dir: /usr/src/redhat/RPMS/x86_64
    xfsprogs_srpm: xfsprogs-2.9.4-1.el5.centos.src.rpm
    xfsprogs_rpms:
       - filename: xfsprogs-2.9.4-1.1.el5.x86_64.rpm
       - filename: xfsprogs-devel-2.9.4-1.1.el5.x86_64.rpm

  roles:
    - common
  
  tasks:
    - stat: path=/usr/lib64/libxfs.a
      register: _libxfs

    - name: download xfsprogs source
      shell: yumdownloader --source xfsprogs &&
             rpm -ivh "{{ xfsprogs_srpm }}"
      when: _libxfs.stat.exists == false

    - name: patching xfsprogs source
      shell: rpmbuild -bp SPECS/xfsprogs.spec &&
             cp /vagrant/files/centos5/xfsprogs-2.9.4-1.1.el5.xfsprogs.spec SPECS/xfsprogs.spec
      args:
        chdir: /usr/src/redhat/
      when: _libxfs.stat.exists == false

    - name: build xfsprogs and xfsprogs-devel with libxfs
      shell: rpmbuild -ba --define="dist .el5" SPECS/xfsprogs.spec
      args:
        chdir: /usr/src/redhat/ 
      when: _libxfs.stat.exists == false

    - name: remove/clenup xfsprogs packages
      yum: name="{{ item }}" state=absent
      with_items:
        - xfsprogs
        - xfsporgs-devel
      when: _libxfs.stat.exists == false

    - name: install xfsprogs and xfsprogs-devel with libxfs
      shell: rpm -ivh xfsprogs-2.9.4-1.1.el5.x86_64.rpm xfsprogs-devel-2.9.4-1.1.el5.x86_64.rpm
      args:
        chdir: /usr/src/redhat/RPMS/x86_64/ 
      when: _libxfs.stat.exists == false
