---
# tasks file for SeiichiDomyo.libxfs

- hosts: centos6
  sudo: yes

  vars:
    xfsprogs_rpms_dir: /home/vagrant/rpmbuild/RPMS/x86_64
    xfsprogs_srpm: xfsprogs-3.1.1-16.el6.src.rpm
    xfsprogs_rpms:
       - filename: xfsprogs-3.1.1-16.el6.x86_64.rpm
       - filename: xfsprogs-devel-3.1.1-16.el6.x86_64.rpm
       - filename: xfsprogs-qa-devel-3.1.1-16.el6.x86_64.rpm

  roles:
    - common

  tasks:
    - stat: path=/usr/lib64/libxfs.so
      register: _libxfs

    - name: setup yum repo 
      shell: cp /vagrant/files/CentOS6-Source.repo /etc/yum.repos.d/CentOS-Source.repo
      when: _libxfs.stat.exists == false

    - name: download xfsprogs source
      sudo: no
      shell: yumdownloader --source xfsprogs &&
             rpm -ivh "{{ xfsprogs_srpm }}"
      when: _libxfs.stat.exists == false

    - name: patching xfsprogs source
      sudo: no
      shell: rpmbuild -bp SPECS/xfsprogs.spec &&
             cp /vagrant/files/xfsprogs-3.1.1-install-libxfs.patch SOURCES/ &&
             cp /vagrant/files/xfsprogs-3.1.1-xfsprogs.spec SPECS/xfsprogs.spec
      args:
        chdir: ~/rpmbuild/
      when: _libxfs.stat.exists == false

    - name: build xfsprogs and xfsprogs-devel with libxfs
      sudo: no
      shell: rpmbuild -ba SPECS/xfsprogs.spec
      args:
        chdir: ~/rpmbuild/
      when: _libxfs.stat.exists == false

    - name: remove/clenup xfsprogs packages
      yum: name="{{ item }}" state=absent
      with_items:
        - xfsprogs
        - xfsporgs-devel
      when: _libxfs.stat.exists == false

    - name: install xfsprogs and xfsprogs-devel with libxfs
      yum: name="{{ xfsprogs_rpms_dir }}/{{ item.filename }}" state=present
      with_items: xfsprogs_rpms
      when: _libxfs.stat.exists == false
