- name: check xfsprogs and xfsprogs-devel rpms 
  yum:
    name: "{{ rpmbuild_rpms_dir }}/{{ item.filename }}"
    disable_gpg_check: yes
    state: present
  with_items: "{{ xfsprogs_rpms }}"
  register: installed_xfsprogs
  when:
    - installation_xfsprogs
  ignore_errors: true

- name: install some packages for build
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libtool
    - gettext
    - libattr-devel
    - libuuid-devel
    - readline-devel
    - libblkid-devel
  when:
    - installation_xfsprogs

- name: download xfsprogs source
  become: no
  get_url:
    url: "{{ xfsprogs_srpm_url }}"
    dest: "{{ rpmbuild_user_home }}"
  when:
    - installation_xfsprogs

- name: expand xfsprogs source
  become: no 
  command: rpm -ivh "{{ xfsprogs_srpm_filename }}"
  args:
    chdir: "{{ rpmbuild_user_home }}"
  when:
    - installation_xfsprogs
    - installed_xfsprogs | failed

- name: patching xfsprogs source
  become: no
  command: cp /vagrant/files/centos7/xfsprogs-4.5.0-9.1.el7_3-xfsprogs.spec SPECS/xfsprogs.spec
  args:
    chdir: "{{rpmbuild_build_dir }}"
  when:
   - installation_xfsprogs
   - installed_xfsprogs | failed

- name: build xfsprogs and xfsprogs-devel with libxfs
  become: no 
  command: rpmbuild -ba SPECS/xfsprogs.spec
  args:
    chdir: "{{rpmbuild_build_dir }}" 
  when:
    - installation_xfsprogs
    - installed_xfsprogs | failed
 
- name: install xfsprogs and xfsprogs-devel with libxfs
  yum:
    name: "{{ rpmbuild_rpms_dir }}/{{ item.filename }}"
    disable_gpg_check: yes
    state: present
  with_items: "{{ xfsprogs_rpms }}"
  when:
    - installation_xfsprogs
