- name: install some packages for build
  yum: name="{{ item }}" state=present
  with_items:
    - libtool
    - gettext
    - libattr-devel
    - libuuid-devel
    - readline-devel
    - libblkid-devel
