installation_xfsprogs: true 

rpmbuild_dir: /home/vagrant/rpmbuild/
rpms_dir: /home/vagrant/rpmbuild/RPMS/x86_64
xfsprogs_srpm: xfsprogs-4.5.0-9.el7_3.src.rpm
xfsprogs_rpms:
   - filename: xfsprogs-4.5.0-9.1.el7.centos.x86_64.rpm
   - filename: xfsprogs-devel-4.5.0-9.1.el7.centos.x86_64.rpm
