- name: install yumdownloader package
  yum: name="yum-utils" state=present

- name: install the Development tools packages
  yum: name="@development" state=present

- name: install rpmbuild
  yum: name="{{ item }}" state=present
  with_items:
    - rpmdevtools
