- name: install yumdownloader package
  yum: name="yum-utils" state=present

- name: install the Development tools packages
  yum: name="@development" state=present

- name: install some packages for rebuild
  yum: name="{{ item }}" state=present
  with_items:
    - rpmdevtools
    - readline-devel
    - libblkid-devel
    - libuuid-devel
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '6'

- name: install some packages for rebuild
  yum: name="{{ item }}" state=present
  with_items:
    - libtool
    - autoconf
    - gettext
    - rpmdevtools
    - readline-devel
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == '5'
